### ISSUE TITLE
What happened?

### ISSUE THREAD

**Issue by DarkXShadowX21** [alex-alex/ingress-for-glass-old#1]
What happened with Ingress @alex-alex?

**Comment by alex-alex** [comment]
Unfortunately, Niantic took it down.

http://ios-ingress.com/?topic=133.0

**Comment by DarkXShadowX21** [comment]
Sorry to hear about this @alex-alex. My newest Level 4 account at 108 AP was shut down at 1:10pm today. While I was out driving to a portal :/

What about contacting Niantic Labs and finding out if you can be any of assistance on an official iOS port of Ingress? 

Having an iOS version officially would be the only thing that would make sense at this point. You don't want to get all tangled up in legalities with Google. That would just not end up well.

**Comment by alex-alex** [comment]
Yes, that would be really great, except they are not responding on my emails and just shutting down everything they can.

**Comment by DarkXShadowX21** [comment]
That's unfortunate. So much for any kind of encouragement towards developers. It seems like Niantic has their own "click" and don't want any outsiders to be apart of it. 

As far as Ingress only being available on Android, it's pretty much unfair to the iOS players. The iOS Ingress community has built up to a large number player base that it's surprising that Ingress hasn't already released an official iOS version of their own. They talked briefly about an iOS version about 9 months ago. Since then, not a word about it.
